name: Build and Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Compile LaTeX
      uses: xu-cheng/latex-action@master
      with:
        root_file: subcommittee_regulations.tex
    - name: Deploy
      uses: docker://peaceiris/gh-pages:latest
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./
      with:
        emptyCommits: false
